### ISSUE TITLE
[Improve Vis] add relative marker size

### ISSUE THREAD

**Issue by yyyxam** [mala-project/malaWeb#14]
As described by [these properties](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Scatter3d.html#plotly.graph_objects.scatter3d.Marker.size), visualize density not only by color but also by size.

It would be nice to be able to do this to opacity too, but that [property](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Scatter3d.html#plotly.graph_objects.scatter3d.Marker.opacity) only accepts constant values.

**Comment by mxyyz** [comment]
Maybe add settings-option to turn this off and to set min/max size values

**Comment by mxyyz** [comment]
Maybe don't do this, so that markers keep representing voxel size (to some extent)
